INSERT INTO pais (NOME) VALUES ('Afeganistão');
INSERT INTO pais (NOME) VALUES ('África do Sul');
INSERT INTO pais (NOME) VALUES ('Åland, Ilhas');
INSERT INTO pais (NOME) VALUES ('Albânia');
INSERT INTO pais (NOME) VALUES ('Alemanha');
INSERT INTO pais (NOME) VALUES ('Andorra');
INSERT INTO pais (NOME) VALUES ('Angola');
INSERT INTO pais (NOME) VALUES ('Anguilla');
INSERT INTO pais (NOME) VALUES ('Antárctida');
INSERT INTO pais (NOME) VALUES ('Antigua e Barbuda');
INSERT INTO pais (NOME) VALUES ('Antilhas Holandesas');
INSERT INTO pais (NOME) VALUES ('Arábia Saudita');
INSERT INTO pais (NOME) VALUES ('Argélia');
INSERT INTO pais (NOME) VALUES ('Argentina');
INSERT INTO pais (NOME) VALUES ('Arménia');
INSERT INTO pais (NOME) VALUES ('Aruba');
INSERT INTO pais (NOME) VALUES ('Austrália');
INSERT INTO pais (NOME) VALUES ('Áustria');
INSERT INTO pais (NOME) VALUES ('Azerbeijão');
INSERT INTO pais (NOME) VALUES ('Bahamas');
INSERT INTO pais (NOME) VALUES ('Bahrain');
INSERT INTO pais (NOME) VALUES ('Bangladesh');
INSERT INTO pais (NOME) VALUES ('Barbados');
INSERT INTO pais (NOME) VALUES ('Bélgica');
INSERT INTO pais (NOME) VALUES ('Belize');
INSERT INTO pais (NOME) VALUES ('Benin');
INSERT INTO pais (NOME) VALUES ('Bermuda');
INSERT INTO pais (NOME) VALUES ('Bielo-Rússia');
INSERT INTO pais (NOME) VALUES ('Bolívia');
INSERT INTO pais (NOME) VALUES ('Bósnia-Herzegovina');
INSERT INTO pais (NOME) VALUES ('Botswana');
INSERT INTO pais (NOME) VALUES ('Bouvet, Ilha');
INSERT INTO pais (NOME) VALUES ('Brasil');
INSERT INTO pais (NOME) VALUES ('Brunei');
INSERT INTO pais (NOME) VALUES ('Bulgária');
INSERT INTO pais (NOME) VALUES ('Burkina Faso');
INSERT INTO pais (NOME) VALUES ('Burundi');
INSERT INTO pais (NOME) VALUES ('Butão');
INSERT INTO pais (NOME) VALUES ('Cabo Verde');
INSERT INTO pais (NOME) VALUES ('Cambodja');
INSERT INTO pais (NOME) VALUES ('Camarões');
INSERT INTO pais (NOME) VALUES ('Canadá');
INSERT INTO pais (NOME) VALUES ('Cayman, Ilhas');
INSERT INTO pais (NOME) VALUES ('Cazaquistão');
INSERT INTO pais (NOME) VALUES ('Centro-africana, República');
INSERT INTO pais (NOME) VALUES ('Chade');
INSERT INTO pais (NOME) VALUES ('Checa, República');
INSERT INTO pais (NOME) VALUES ('Chile');
INSERT INTO pais (NOME) VALUES ('China');
INSERT INTO pais (NOME) VALUES ('Chipre');
INSERT INTO pais (NOME) VALUES ('Christmas, Ilha');
INSERT INTO pais (NOME) VALUES ('Cocos, Ilhas');
INSERT INTO pais (NOME) VALUES ('Colômbia');
INSERT INTO pais (NOME) VALUES ('Comores');
INSERT INTO pais (NOME) VALUES ('Congo, República do');
INSERT INTO pais (NOME) VALUES ('Congo, República Democrática do');
INSERT INTO pais (NOME) VALUES ('Cook, Ilhas');
INSERT INTO pais (NOME) VALUES ('Coreia do Sul');
INSERT INTO pais (NOME) VALUES ('Coreia do Norte');
INSERT INTO pais (NOME) VALUES ('Costa do Marfim');
INSERT INTO pais (NOME) VALUES ('Costa Rica');
INSERT INTO pais (NOME) VALUES ('Croácia');
INSERT INTO pais (NOME) VALUES ('Cuba');
INSERT INTO pais (NOME) VALUES ('Dinamarca');
INSERT INTO pais (NOME) VALUES ('Djibouti');
INSERT INTO pais (NOME) VALUES ('Dominica');
INSERT INTO pais (NOME) VALUES ('Dominicana, República');
INSERT INTO pais (NOME) VALUES ('Egipto');
INSERT INTO pais (NOME) VALUES ('El Salvador');
INSERT INTO pais (NOME) VALUES ('Emiratos Árabes Unidos');
INSERT INTO pais (NOME) VALUES ('Equador');
INSERT INTO pais (NOME) VALUES ('Eritreia');
INSERT INTO pais (NOME) VALUES ('Eslováquia');
INSERT INTO pais (NOME) VALUES ('Eslovénia');
INSERT INTO pais (NOME) VALUES ('Espanha');
INSERT INTO pais (NOME) VALUES ('Estados Unidos da América');
INSERT INTO pais (NOME) VALUES ('Estónia');
INSERT INTO pais (NOME) VALUES ('Etiópia');
INSERT INTO pais (NOME) VALUES ('Faroe, Ilhas');
INSERT INTO pais (NOME) VALUES ('Fiji');
INSERT INTO pais (NOME) VALUES ('Filipinas');
INSERT INTO pais (NOME) VALUES ('Finlândia');
INSERT INTO pais (NOME) VALUES ('França');
INSERT INTO pais (NOME) VALUES ('Gabão');
INSERT INTO pais (NOME) VALUES ('Gâmbia');
INSERT INTO pais (NOME) VALUES ('Gana');
INSERT INTO pais (NOME) VALUES ('Geórgia');
INSERT INTO pais (NOME) VALUES ('Geórgia do Sul e Sandwich do Sul, Ilhas');
INSERT INTO pais (NOME) VALUES ('Gibraltar');
INSERT INTO pais (NOME) VALUES ('Grécia');
INSERT INTO pais (NOME) VALUES ('Grenada');
INSERT INTO pais (NOME) VALUES ('Gronelândia');
INSERT INTO pais (NOME) VALUES ('Guadeloupe');
INSERT INTO pais (NOME) VALUES ('Guam');
INSERT INTO pais (NOME) VALUES ('Guatemala');
INSERT INTO pais (NOME) VALUES ('Guernsey');
INSERT INTO pais (NOME) VALUES ('Guiana');
INSERT INTO pais (NOME) VALUES ('Guiana Francesa');
INSERT INTO pais (NOME) VALUES ('Guiné-Bissau');
INSERT INTO pais (NOME) VALUES ('Guiné-Conacri');
INSERT INTO pais (NOME) VALUES ('Guiné Equatorial');
INSERT INTO pais (NOME) VALUES ('Haiti');
INSERT INTO pais (NOME) VALUES ('Heard e Ilhas McDonald, Ilha');
INSERT INTO pais (NOME) VALUES ('Holanda');
INSERT INTO pais (NOME) VALUES ('Honduras');
INSERT INTO pais (NOME) VALUES ('Hong Kong');
INSERT INTO pais (NOME) VALUES ('Hungria');
INSERT INTO pais (NOME) VALUES ('Iémen');
INSERT INTO pais (NOME) VALUES ('Índia');
INSERT INTO pais (NOME) VALUES ('Indonésia');
INSERT INTO pais (NOME) VALUES ('Iraque');
INSERT INTO pais (NOME) VALUES ('Irão');
INSERT INTO pais (NOME) VALUES ('Irlanda');
INSERT INTO pais (NOME) VALUES ('Islândia');
INSERT INTO pais (NOME) VALUES ('Israel');
INSERT INTO pais (NOME) VALUES ('Itália');
INSERT INTO pais (NOME) VALUES ('Jamaica');
INSERT INTO pais (NOME) VALUES ('Japão');
INSERT INTO pais (NOME) VALUES ('Jersey');
INSERT INTO pais (NOME) VALUES ('Jordânia');
INSERT INTO pais (NOME) VALUES ('Kiribati');
INSERT INTO pais (NOME) VALUES ('Kuwait');
INSERT INTO pais (NOME) VALUES ('Laos');
INSERT INTO pais (NOME) VALUES ('Lesoto');
INSERT INTO pais (NOME) VALUES ('Letónia');
INSERT INTO pais (NOME) VALUES ('Líbano');
INSERT INTO pais (NOME) VALUES ('Libéria');
INSERT INTO pais (NOME) VALUES ('Líbia');
INSERT INTO pais (NOME) VALUES ('Liechtenstein');
INSERT INTO pais (NOME) VALUES ('Lituânia');
INSERT INTO pais (NOME) VALUES ('Luxemburgo');
INSERT INTO pais (NOME) VALUES ('Macau');
INSERT INTO pais (NOME) VALUES ('Macedónia, República da');
INSERT INTO pais (NOME) VALUES ('Madagáscar');
INSERT INTO pais (NOME) VALUES ('Malásia');
INSERT INTO pais (NOME) VALUES ('Malawi');
INSERT INTO pais (NOME) VALUES ('Maldivas');
INSERT INTO pais (NOME) VALUES ('Mali');
INSERT INTO pais (NOME) VALUES ('Malta');
INSERT INTO pais (NOME) VALUES ('Malvinas, Ilhas (Falkland)');
INSERT INTO pais (NOME) VALUES ('Man, Ilha de');
INSERT INTO pais (NOME) VALUES ('Marianas Setentrionais');
INSERT INTO pais (NOME) VALUES ('Marrocos');
INSERT INTO pais (NOME) VALUES ('Marshall, Ilhas');
INSERT INTO pais (NOME) VALUES ('Martinica');
INSERT INTO pais (NOME) VALUES ('Maurícia');
INSERT INTO pais (NOME) VALUES ('Mauritânia');
INSERT INTO pais (NOME) VALUES ('Mayotte');
INSERT INTO pais (NOME) VALUES ('Menores Distantes dos Estados Unidos, Ilhas');
INSERT INTO pais (NOME) VALUES ('México');
INSERT INTO pais (NOME) VALUES ('Myanmar (antiga Birmânia)');
INSERT INTO pais (NOME) VALUES ('Micronésia, Estados Federados da');
INSERT INTO pais (NOME) VALUES ('Moçambique');
INSERT INTO pais (NOME) VALUES ('Moldávia');
INSERT INTO pais (NOME) VALUES ('Mónaco');
INSERT INTO pais (NOME) VALUES ('Mongólia');
INSERT INTO pais (NOME) VALUES ('Montenegro');
INSERT INTO pais (NOME) VALUES ('Montserrat');
INSERT INTO pais (NOME) VALUES ('Namíbia');
INSERT INTO pais (NOME) VALUES ('Nauru');
INSERT INTO pais (NOME) VALUES ('Nepal');
INSERT INTO pais (NOME) VALUES ('Nicarágua');
INSERT INTO pais (NOME) VALUES ('Níger');
INSERT INTO pais (NOME) VALUES ('Nigéria');
INSERT INTO pais (NOME) VALUES ('Niue');
INSERT INTO pais (NOME) VALUES ('Norfolk, Ilha');
INSERT INTO pais (NOME) VALUES ('Noruega');
INSERT INTO pais (NOME) VALUES ('Nova Caledónia');
INSERT INTO pais (NOME) VALUES ('Nova Zelândia');
INSERT INTO pais (NOME) VALUES ('Oman');
INSERT INTO pais (NOME) VALUES ('Palau');
INSERT INTO pais (NOME) VALUES ('Palestina');
INSERT INTO pais (NOME) VALUES ('Panamá');
INSERT INTO pais (NOME) VALUES ('Papua-Nova Guiné');
INSERT INTO pais (NOME) VALUES ('Paquistão');
INSERT INTO pais (NOME) VALUES ('Paraguai');
INSERT INTO pais (NOME) VALUES ('Peru');
INSERT INTO pais (NOME) VALUES ('Pitcairn');
INSERT INTO pais (NOME) VALUES ('Polinésia Francesa');
INSERT INTO pais (NOME) VALUES ('Polónia');
INSERT INTO pais (NOME) VALUES ('Porto Rico');
INSERT INTO pais (NOME) VALUES ('Portugal');
INSERT INTO pais (NOME) VALUES ('Qatar');
INSERT INTO pais (NOME) VALUES ('Quénia');
INSERT INTO pais (NOME) VALUES ('Quirguistão');
INSERT INTO pais (NOME) VALUES ('Reino Unido da Grã-Bretanha e Irlanda do Norte');
INSERT INTO pais (NOME) VALUES ('Reunião');
INSERT INTO pais (NOME) VALUES ('Roménia');
INSERT INTO pais (NOME) VALUES ('Ruanda');
INSERT INTO pais (NOME) VALUES ('Rússia');
INSERT INTO pais (NOME) VALUES ('Saara Ocidental');
INSERT INTO pais (NOME) VALUES ('Samoa Americana');
INSERT INTO pais (NOME) VALUES ('Samoa (Samoa Ocidental)');
INSERT INTO pais (NOME) VALUES ('Saint Pierre et Miquelon');
INSERT INTO pais (NOME) VALUES ('Salomão, Ilhas');
INSERT INTO pais (NOME) VALUES ('São Cristóvão e Névis');
INSERT INTO pais (NOME) VALUES ('San Marino');
INSERT INTO pais (NOME) VALUES ('São Tomé e Príncipe');
INSERT INTO pais (NOME) VALUES ('São Vicente e Granadinas');
INSERT INTO pais (NOME) VALUES ('Santa Helena');
INSERT INTO pais (NOME) VALUES ('Santa Lúcia');
INSERT INTO pais (NOME) VALUES ('Senegal');
INSERT INTO pais (NOME) VALUES ('Serra Leoa');
INSERT INTO pais (NOME) VALUES ('Sérvia');
INSERT INTO pais (NOME) VALUES ('Seychelles');
INSERT INTO pais (NOME) VALUES ('Singapura');
INSERT INTO pais (NOME) VALUES ('Síria');
INSERT INTO pais (NOME) VALUES ('Somália');
INSERT INTO pais (NOME) VALUES ('Sri Lanka');
INSERT INTO pais (NOME) VALUES ('Suazilândia');
INSERT INTO pais (NOME) VALUES ('Sudão');
INSERT INTO pais (NOME) VALUES ('Suécia');
INSERT INTO pais (NOME) VALUES ('Suíça');
INSERT INTO pais (NOME) VALUES ('Suriname');
INSERT INTO pais (NOME) VALUES ('Svalbard e Jan Mayen');
INSERT INTO pais (NOME) VALUES ('Tailândia');
INSERT INTO pais (NOME) VALUES ('Taiwan');
INSERT INTO pais (NOME) VALUES ('Tajiquistão');
INSERT INTO pais (NOME) VALUES ('Tanzânia');
INSERT INTO pais (NOME) VALUES ('Terras Austrais e Antárticas Francesas (TAAF)');
INSERT INTO pais (NOME) VALUES ('Território Britânico do Oceano Índico');
INSERT INTO pais (NOME) VALUES ('Timor-Leste');
INSERT INTO pais (NOME) VALUES ('Togo');
INSERT INTO pais (NOME) VALUES ('Toquelau');
INSERT INTO pais (NOME) VALUES ('Tonga');
INSERT INTO pais (NOME) VALUES ('Trindade e Tobago');
INSERT INTO pais (NOME) VALUES ('Tunísia');
INSERT INTO pais (NOME) VALUES ('Turks e Caicos');
INSERT INTO pais (NOME) VALUES ('Turquemenistão');
INSERT INTO pais (NOME) VALUES ('Turquia');
INSERT INTO pais (NOME) VALUES ('Tuvalu');
INSERT INTO pais (NOME) VALUES ('Ucrânia');
INSERT INTO pais (NOME) VALUES ('Uganda');
INSERT INTO pais (NOME) VALUES ('Uruguai');
INSERT INTO pais (NOME) VALUES ('Usbequistão');
INSERT INTO pais (NOME) VALUES ('Vanuatu');
INSERT INTO pais (NOME) VALUES ('Vaticano');
INSERT INTO pais (NOME) VALUES ('Venezuela');
INSERT INTO pais (NOME) VALUES ('Vietname');
INSERT INTO pais (NOME) VALUES ('Virgens Americanas, Ilhas');
INSERT INTO pais (NOME) VALUES ('Virgens Britânicas, Ilhas');
INSERT INTO pais (NOME) VALUES ('Wallis e Futuna');
INSERT INTO pais (NOME) VALUES ('Zâmbia');
INSERT INTO pais (NOME) VALUES ('Zimbabwe');

